#!/usr/bin/env node
/**
 * Cross-platform i18n compile script.
 * Compiles all JSON message files in src/i18n/messages/ using formatjs,
 * then generates a menu-only translation catalog for the main process.
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const projectDir = path.join(__dirname, '..');
const formatjs = require.resolve('@formatjs/cli/bin/formatjs');
const messagesDir = path.join(projectDir, 'src', 'i18n', 'messages');
const compiledDir = path.join(projectDir, 'src', 'i18n', 'compiled');
const generatedDir = path.join(projectDir, 'src', 'i18n', 'generated');

fs.mkdirSync(compiledDir, { recursive: true });
fs.mkdirSync(generatedDir, { recursive: true });

const files = fs.readdirSync(messagesDir).filter((f) => f.endsWith('.json'));

for (const file of files) {
  const locale = path.basename(file, '.json');
  const inFile = path.join(messagesDir, file).split(path.sep).join('/');
  const outFile = path.join(compiledDir, `${locale}.json`);
  execFileSync(process.execPath, [formatjs, 'compile', inFile, '--out-file', outFile], {
    stdio: 'inherit',
    cwd: projectDir,
  });
}
// Generate a menu-only translation catalog for the main process.
// English defaults come from compiled en.json (extracted from defineMessages
// in src/utils/menu.ts). Non-English locales only include menu.* keys whose value
// differs from the English default.
function generateMenuTranslations() {
  const enCompiled = JSON.parse(fs.readFileSync(path.join(compiledDir, 'en.json'), 'utf8'));

  const menuDefaults = {};
  for (const [key, value] of Object.entries(enCompiled)) {
    if (key.startsWith('menu.') && typeof value === 'string') {
      menuDefaults[key] = value;
    }
  }

  const menuTranslations = {};
  for (const file of files) {
    const locale = path.basename(file, '.json');
    if (locale === 'en') continue;

    const compiledPath = path.join(compiledDir, locale + '.json');
    if (!fs.existsSync(compiledPath)) continue;

    const compiled = JSON.parse(fs.readFileSync(compiledPath, 'utf8'));
    const translations = {};
    for (const [key, value] of Object.entries(compiled)) {
      if (!key.startsWith('menu.')) continue;
      if (typeof value !== 'string') continue;
      if (value === menuDefaults[key]) continue;
      translations[key] = value;
    }

    if (Object.keys(translations).length > 0) {
      menuTranslations[locale] = translations;
    }
  }

  const outPath = path.join(generatedDir, 'menuTranslations.ts');
  const header = '// Auto-generated by i18n-compile.js - do not edit\n';
  const body =
    'export const MENU_TRANSLATIONS: Record<string, Record<string, string>> = ' +
    JSON.stringify(menuTranslations, null, 2) +
    ';\n';

  fs.writeFileSync(outPath, header + body, 'utf8');
  console.log(
    'i18n-compile: generated menu translations for ' +
      Object.keys(menuTranslations).length +
      ' locale(s)'
  );
}

generateMenuTranslations();
